title: Sam Younger
email: samyounger@foobox.com
description: >
  This is a website by Sam Younger describing his path to becoming a web developer, and a blog discussing web development learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.samyounger.com"
# repository: samyounger/samyounger.github.io
# twitter_username: ayoungersage
# github_username:  samyounger

# Footer settings
footer: Sam Younger

# Social networks
social:
  - title: twitter
    url: https://twitter.com/ayoungersam
  - title: facebook
    url: https://facebook.com/sam.younger1
  - title: stack-overflow
    url: http://stackoverflow.com/story/samyounger
  - title: linkedin
    url: http://linkedin.com/in/sam-younger
  - title: github
    url: https://github.com/samyounger

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# How to structure post paths https://jekyllrb.com/docs/permalinks
permalink: /:year-:month-:day-:title

# Default layouts for pages
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      author: "Sam Younger"
      published: true
