assets:
  compress:
      css: true
      js: true
  features:
    automatic_img_size: false
  assets:
    - "*.png"
    - "*.jpg"
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md

ga_analytics: # Add Google Analytics tracking code

gems:
  - jekyll-assets
  - jekyll-sitemap


# Build settings
permalink: pretty
markdown: kramdown

url: samyounger.com

# Site settings
name: Sam Younger
email: sam.younger@gmail.com
description: |
  Welcome to my website

# Footer settings
footer: Sam Younger

# Social networks
social:
  - title: twitter
    url: https://twitter.com/ayoungersage
  - title: facebook
    url: https://facebook.com/sam.younger1
  - title: stack-overflow
    url: http://stackoverflow.com/story/samyounger
  - title: linkedin
    url: http://linkedin.com/in/sam-younger
  - title: github
    url: https://github.com/samyounger
