# Site settings
title: Sam Younger
email: sam.younger@gmail.com
url: ""
description: |
  Welcome to my website

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#FFD85F'

# Footer settings
footer: Sam Younger

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ayoungersage
  - title: facebook
    url: https://facebook.com/sam.younger1
  - title: stack-overflow
    url: http://stackoverflow.com/story/samyounger
  - title: linkedin
    url: http://linkedin.com/in/sam-younger
  - title: github
    url: https://github.com/samyounger

# Build settings
markdown: kramdown
permalink: pretty
