url: https://samyounger.github.io
baseurl: ""

# Site settings
title: Sam Younger
email: sam.younger@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Sam younger
  pic: 1
  position: Web Developer
  social:
    - title: twitter
      url: https://twitter.com/aYoungerSage
    - title: linkedin
      url: https://uk.linkedin.com/in/sam-younger

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ayoungersage
  - title: facebook
    url: https://www.facebook.com/sam.younger1
  - title: stack-overflow
    url: http://stackoverflow.com/story/samyounger
  - title: linkedin
    url: https://uk.linkedin.com/in/sam-younger
  - title: github
    url: http://github.com/samyounger

# Postal address (add as many lines as necessary)
address:
  - line:Flat 4 Shams Court, 25 Fulton Road
  - line: London, HA9 0GA

# Build settings
markdown: kramdown
permalink: pretty
